### ISSUE TITLE
Error 500 when installing from plugin Repo

### ISSUE THREAD

**Issue by Ixoran** [fulder/iocage-plugin-bazarr#8]
When istalling from community plugins on TrueNAS, i get an error 500.

**Comment by Ixoran** [comment]
Looks like it was my fault

**Comment by fulder** [comment]
@Ixoran, what was the issue and how did you solve it, if I may ask? :smile: I'm seeing the 500 error as well and I think it's because of a recent change in installation instructions and removal of git for bazarr updates. I will start working on a fix to support the new way this plugin should be installed.

**Comment by Ixoran** [comment]
@fulder All I did was restart Bazaar, I was moving around some services on the network, but I'm not sure it was related.
